### ISSUE TITLE
Freezing ticks are never removed from dummies

### ISSUE THREAD

**Issue by Dariensg** [MehVahdJukaar/Dummy_1.18#14]
I'm writing this report on behalf of a user of my mod, just so I can get the details right for them.

In your DummyEntity, you override tick but never call aiStep. This means that powdered snow doesn't give freezing ticks to the dummies, which is fine. But if other damage sources, such as modded ones (the case here) give freezing ticks to the dummies through attacks or otherwise, aiStep also is responsible for ticking those down. This means that a dummy will never remove the freezing ticks and will continue to shake as frozen eternally. And, since freezing ticks are saved to NBT, this continues even after exiting game and resuming.

I'd suggest either still calling aiStep, or just adding in your own logic for reducing freezing ticks on the dummies. Since they extend Mob, they're indistinguishable from other entities, and thus can't really have a special case in the freezing ticks application unless I specifically pulled this mod into dev and checked instanceof. It would be much better to have a fix on your end, so not all mod devs have to specially consider the Dummy separately.

Thanks in advance and happy to answer any questions!

**Comment by MehVahdJukaar** [comment]
Probably some 1.18 update stuff I missed. Entity can't ai step and has to manually tick those down like fire as it's nothtechnically living

**Comment by Dariensg** [comment]
Yeah, either method works!

**Comment by MehVahdJukaar** [comment]
fixed. entity now calls living entity base tick
