### ISSUE TITLE
Apotheosis damage display anomaly

### ISSUE THREAD

**Issue by Dr-WeiAL** [MehVahdJukaar/Dummy_1.18#15]
https://github.com/MehVahdJukaar/DuMmmMmmy1.16/issues/24
I just found this repository, so I came here to repeat it

Attacking a dummy with a weapon with Apotheosis affix does not show the damage correctly
It looks like only Fire Damage is shown

The issue still exists in 1.20.1, but the details are slightly different, such as the magic damage color causing white damage

![image](https://github.com/MehVahdJukaar/DuMmmMmmy/assets/47446553/5721af7f-8eab-426e-a2a9-599c88f88552)
![image](https://github.com/MehVahdJukaar/DuMmmMmmy/assets/47446553/f3345622-4ab5-42c1-9a56-b0c145c1212c)

**Comment by MehVahdJukaar** [comment]
Unfortunately I'm only supporting 1.20, maybe 1.19 verisons

**Comment by Dr-WeiAL** [comment]
> Unfortunately I'm only supporting 1.20, maybe 1.19 verisons

Uh... I was actually talking about version 1.20.1, just borrowing from a previous issue
This problem has existed for a long time and still exists until 1.20.1

**Comment by Dr-WeiAL** [comment]
![image](https://github.com/MehVahdJukaar/DuMmmMmmy/assets/47446553/1237f92f-c483-4818-bf6a-1e023507eb3c)
![image](https://github.com/MehVahdJukaar/DuMmmMmmy/assets/47446553/c31d758c-3d9e-4940-a2eb-885fe05bd2ff)
This is the 1.20.1 version I just tested
Not only does it only show magic damage, but the magic damage also turns white
If it's a mod that adds other damage types, is it possible to add a config to customize the colors that damage types display?

**Comment by MehVahdJukaar** [comment]
ah my bad. I'll look into it eventually but sounds like a very complicated issue

**Comment by Dr-WeiAL** [comment]
Hold the weapon in your hand and type `/apoth lootify apotheosis:ancient` to get the attribute
This problem can be reproduced if there is Fire Damage or Cold Damage in the properties.

**Comment by MehVahdJukaar** [comment]
fixed
