### ISSUE TITLE
Suggestion: show Damage Type somehow

### ISSUE THREAD

**Issue by Partonetrain** [MehVahdJukaar/Dummy_1.18#22]
Since 1.19.4 added data-driven data types, it could be handy to test what kind of damage type a weapon or projectile uses.
Since this won't be useful for most end-users, maybe it could be F3 or gamerule only.

**Comment by MehVahdJukaar** [comment]
You can already do this. Mod always showed different colour for each damave type

**Comment by Partonetrain** [comment]
I didn't notice that 😅, but I was referring to the IDs/ResourceLocation of damage types, like if I were to add one via a mod.

**Comment by MehVahdJukaar** [comment]
This can be added via config
