### ISSUE TITLE
Crash on Fabric 1.19.2/0.14.12

### ISSUE THREAD

**Issue by pokesmells** [MehVahdJukaar/Dummy_1.18#3]
[crash-2023-01-04_18.41.36-server.txt](https://github.com/MehVahdJukaar/DuMmmMmmy/files/10348529/crash-2023-01-04_18.41.36-server.txt)
[crash-2023-01-04_18.51.18-server.txt](https://github.com/MehVahdJukaar/DuMmmMmmy/files/10348530/crash-2023-01-04_18.51.18-server.txt)

STEPS TO REPRODUCE:

Update to dummmmmmy-1.19.2-1.6.1-fabric.jar

Load in to a previously created world, or try and make a new one.

Crashes on load in to said world.

**Comment by MehVahdJukaar** [comment]
It's sodium. It doesn't like something I do with inconsistent behavior from vanilla

**Comment by MehVahdJukaar** [comment]
Also lithium my bad
