### ISSUE TITLE
Crash while joining world

### ISSUE THREAD

**Issue by Dekamir** [MehVahdJukaar/Dummy_1.18#4]
**Happens on:**
dummmmmmy-1.19.2-1.6.1-fabric.jar _and_ dummmmmmy-1.19.2-1.6.0-fabric.jar

**Does not occur on:**
MmmMmmMmmMmm-FABRIC-1.18-1.5.3.jar

[(Text) Crash Log](https://github.com/MehVahdJukaar/DuMmmMmmy/files/10348541/crash-2023-01-05_04.07.24-server.txt)
[(Text) Full Log](https://github.com/MehVahdJukaar/DuMmmMmmy/files/10348545/latest.log)

**Environment:**
Minecraft 1.19.2
Default Minecraft Launcher Java RE
Fabric 0.14.11 _and_ 0.14.12
Windows 10 Pro 21H2 (en_US, tr_TR)
[(Text) Mod List](https://github.com/MehVahdJukaar/DuMmmMmmy/files/10348552/modlist.txt)

**Comment by MehVahdJukaar** [comment]
Lithium has no way to add goals to entities. I released a patch that just disables scarecrow mode on lithium. Forge one remains full feature
