### ISSUE TITLE
Config files are being corrected every second despite it's completely the same

### ISSUE THREAD

**Issue by asrieldashie** [MehVahdJukaar/Dummy_1.18#42]
Minecraft 1.21.1, NeoForge 21.1.50

The config files are being "corrected" each second and causes huge log spam, and the corrected file are exactly the same to the ones before
The issue rarely happens on dedicated server but always happens on desktop
Unsure if it was a mod conflict since the issue doesn't happen when installed without other mods

Same issue also happens to Amendments and Sawmill
[debug.log](https://github.com/user-attachments/files/17004481/debug.log)

**Comment by MehVahdJukaar** [comment]
does this hapen on the newest version?

**Comment by asrieldashie** [comment]
Yes it's fixed
