### ISSUE TITLE
Memory Leak of ServerLevel

### ISSUE THREAD

**Issue by pietro-lopes** [MehVahdJukaar/Dummy_1.18#45]
This is leaking the ServerLevel when unloading the world and loading again.
You need to make sure you clear this or use WeakReference

https://github.com/MehVahdJukaar/DuMmmMmmy/blob/5cea74edc3bfe659f8ab46b23444ee0565aa324f/common/src/main/java/net/mehvahdjukaar/dummmmmmy/mixins/EnchantmentMixin.java#L39

![image](https://github.com/user-attachments/assets/50d213e3-ff0b-4b39-b5e0-70c6bb0aa279)

**Comment by MehVahdJukaar** [comment]
oh noe. yeah it should have been a weak reference. was way nicer in 1.20 when none of these here needed. new enchantment system is very limiting
