### ISSUE TITLE
Target dummy damage particle effect corrupts rendering of other particles

### ISSUE THREAD

**Issue by ZsoltMolnarrr** [MehVahdJukaar/Dummy_1.18#8]
Hello!

Game version: 1.19.2
Loader: Fabric
Mod version: 1.7.0

**Experienced**
When a target dummy is hit and a damage particle pops up, tinted particles from other sources render incorrectly.

https://user-images.githubusercontent.com/4989469/221003822-a7c97174-75e3-46fe-8988-475b88d4fbd4.mov

**Way to reproduce**
Install the following mods:
- MmmMmmMmmMmm
- Sodium, Iris
- Wizards

**Expected**
Particle effects render correctly, while hitting the target dummy.

**Additional information**
Interestingly ToroHealth mod that also shows damage number particles (but on mobs), does not cause the same kind of issue.

**Comment by MehVahdJukaar** [comment]
Thanks, last information is useful. I was aware of this till i reworked them but have no idea why. I'll check out how that mod does it. Must be some gl state that isn't getting cleared

**Comment by MehVahdJukaar** [comment]
fixed

**Comment by ZsoltMolnarrr** [comment]
Thank you!
